development:
  adapter: postgresql
  encoding: unicode
  database: bxg_development
  host: localhost
  pool: 5
  username: eric
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bxg_test
  host: localhost
  pool: 5
  username: eric
  password:
